name: weatherapp
description: Simply aplication using Open Weather Map API

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  retrofit: ^1.3.1
  flutter_simple_dependency_injection: ^1.0.2
  json_serializable: ^3.2.5
  bloc_pattern: ^2.5.1
  rxdart: ^0.23.1
  fluttertoast: ^3.1.3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.1
  build_runner: ^1.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/
